# Build Dependency
gems        : 
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
title       :  nsetyo.web.id
description : 'Blog pribadi tentang Komputer, Programming, dan Linux.'
url         :  https://nsetyo.web.id  # with the https protocol
enforce_ssl :  nsetyo.web.id          # without any protocol

# Author
author:
  name         : nsetyo
  email        : nsetyo.mail@gmail.com
  url          : http://nsetyo.web.id
  facebook     : http://facebook.com/nsetyo
  github       : http://github.com/nsetyo
  twitter      : http://twitter.com/nsetyo

# Default
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"

# Build settings
markdown : kramdown
paginate : 5
paginate_path: "/page/:num/"

