# Build Dependency
gems        : ['jekyll-paginate']

# Site settings
title       :  nsetyo.web.id
description : 'Blog pribadi tentang Komputer, Programming, dan Linux.'
url         :  https://nsetyo.web.id  # with the https protocol
enforce_ssl :  nsetyo.web.id          # without any protocol

# Default settings
default :
  -
    scope:
      path   : "" # an empty string here means all files in the project
      type   : "posts"
    values:
      layout : "posts"
  -
    scope:
      path   : "" # an empty string here means all files in the project
      type   : "pages"
    values:
      layout : "pages"

# Author
author:
  name         : nsetyo
  email        : nsetyo.mail@gmail.com
  url          : http://nsetyo.web.id
  facebook     : http://facebook.com/nsetyo
  github       : http://github.com/nsetyo
  twitter      : http://twitter.com/nsetyo

# Build settings
markdown : kramdown
paginate : 5

